AllCops:
  TargetRubyVersion: 2.5
  Exclude:
   - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
  ExcludedMethods:
    - controllers

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - db/**/*
    - lib/connection_pool_management_middleware.rb

Metrics/ParameterLists:
    CountKeywordArgs:	false
