AllCops:
  TargetRubyVersion: 2.5
  # Exclude:
    # - path/to/files

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - db/**/*
    - lib/connection_pool_management_middleware.rb

Metrics/ParameterLists:
    CountKeywordArgs:	false
